<!DOCTYPE html>
<html lang="en">
<head>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    @livewireStyles
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body class="flex h-screen bg-gray-100" x-data="{
    date_filter: '{{ request('date_filter') }}',
    from_date: '{{ request('from_date') }}',
    to_date: '{{ request('to_date') }}',
    search: '{{ request('search') }}',
    viewGeneratedReport: false,
    reportPath: '',
    clearCustomFilter: function() {
        if (this.date_filter !== 'custom') {
            this.from_date = '';
            this.to_date = '';
        }
    },
    clearFilter: function() {
        this.date_filter = 'all';
        this.from_date = '';
        this.to_date = '';
        this.search = '';

        // Now instead of submitting the form...
        $nextTick(() => {
            // Remove all query parameters without reloading the page
            const url = window.location.origin + window.location.pathname;
            window.history.pushState({}, '', url);

            // THEN submit the form if you want to refresh results
            document.getElementById('filterForm').submit();
        });
    }
}"
>

    @include('super-admin/super-admin-side-panel')

    <div class="relative h-screen flex-1 p-8 overflow-y-scroll">
        <h2 class="text-3xl font-bold mb-10">Generated Reports</h2>

        <!-- Filters -->
        <div class="bg-white p-4 rounded-lg shadow mb-6">
            <h2 class="text-xl font-semibold mb-4 text-gray-700">Filter Reports</h2>
            <!-- Search Input -->
            <div class="relative flex justify-between gap-4 items-center">
                <div class="flex gap-4">
                    
                    
                    <form id="filterForm" method="GET" action="{{ route('go.to.super.admin.generated.report') }}" class="flex flex-wrap justify-between gap-4 items-end">
                        <div class="flex gap-4">
                            <input type="hidden" name="search" value="{{ request('search') }}">
                            <!-- Filter by Date Range -->
                            <div>
                                <label class="block text-sm font-medium text-gray-700 mb-1">Date Filter</label>
                                <select name="date_filter" x-model="date_filter" onchange="this.form.submit()" @click="clearCustomFilter()" class="border p-2 rounded w-52 ">
                                    <option value="all" {{ request('date_filter') == 'all' ? 'selected' : '' }}>All</option>
                                    <option value="today" {{ request('date_filter') == 'today' ? 'selected' : '' }}>Today</option>
                                    <option value="last_3_days" {{ request('date_filter') == 'last_3_days' ? 'selected' : '' }}>Last 3 days</option>
                                    <option value="last_7_days" {{ request('date_filter') == 'last_7_days' ? 'selected' : '' }}>Last 7 days</option>
                                    <option value="custom" {{ request('date_filter') == 'custom' ? 'selected' : '' }}>Custom</option>
                                </select>
                            </div>
                            
                            <div x-cloak x-show="date_filter === 'custom'" class="flex gap-4">
                                <div>
                                    <label class="block text-sm font-medium text-gray-700 mb-1">From Date</label>
                                    <input type="date" name="from_date" x-model="from_date" onchange="this.form.submit()" class="border p-2 rounded w-52 h-[41px]" value="{{ request('from') }}">
                                </div>
                    
                                <div>
                                    <label class="block text-sm font-medium text-gray-700 mb-1">To Date</label>
                                    <input type="date" name="to_date" x-model="to_date" onchange="this.form.submit()" class="border p-2 rounded w-52 h-[41px]" value="{{ request('to') }}">
                                </div>
                            </div>
                        </div>

                        <div x-init="$nextTick(() => { if (search) $refs.searchInput.focus(); })">
                            <label class="block text-sm font-medium text-gray-700 mb-1">Generated By</label>
                            <input x-ref="searchInput" type="text" name="search"  x-model.debounce.500ms="search" class="border p-2 rounded w-64" placeholder="Search name or email..."
                                @input.debounce.500ms="
                                    $nextTick(() => {
                                        $refs.searchInput.blur(); 
                                        window.location.href = `?search=${encodeURIComponent(search)}&date_filter=${date_filter}&from_date=${from_date}&to_date=${to_date}`;
                                    })
                                "
                            >
                        </div>
                        
                        <button type="button" class=" text-blue px-4 py-2 rounded" @click="clearFilter()" >Clear Filter</button>
                    </form>
                </div>
                {{-- <a href="" class="absolute bottom-0 right-5 text-black px-4 py-2 rounded" @click="clearFilter()" >Clear Filter</a> --}}
            </div>
        </div>
    
        @forelse ($generatedReports as $report)
            <a href="#" @click=" reportPath = '{{ asset('storage/' . $report->path) }}'; viewGeneratedReport = true"
                class="block border border-gray-200 bg-white rounded-lg p-4 mb-3 hover:bg-gray-50 transition">
                <div class="flex justify-between items-center">
                    <div>
                        <h3 class="text-md font-semibold text-blue-700">{{ $report->filename }}</h3>
                        <p class="text-sm text-gray-600 mt-1">
                            Generated by: <span class="font-medium">
                            
                                {{ $superAdminUser->where('id', $report->reporter_id)->first()->firstname . ' ' .  $superAdminUser->where('id', $report->reporter_id)->first()->lastname?? 'N/A' }}</span> |
                            {{ $report->created_at->format('M d, Y h:i A') }}
                        </p>
    
                        @if ($report->filters)
                            <div class="text-sm text-gray-500 mt-2">
                                <span class="font-semibold text-gray-600">Filters:</span>
                                <ul class="list-disc list-inside">
                                    @foreach (json_decode($report->filters, true) as $key => $value)
                                        <li><span class="capitalize">{{ str_replace('_', ' ', $key) }}</span>: {{ $value }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @else
                            <p class="text-sm text-gray-400 mt-2 italic">No filters applied</p>
                        @endif
                    </div>
    
                    <div class="text-gray-400">
                        <!-- You could use an icon here -->
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none"
                            viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M17 8l4 4m0 0l-4 4m4-4H3"/>
                        </svg>
                    </div>
                </div>
            </a>
        @empty
            <div class="text-center text-gray-500 italic">No reports generated yet.</div>
        @endforelse
    </div>


    {{-- Show Generated Report --}}
    <div class="fixed inset-0 bg-black bg-opacity-70 flex items-center justify-center p-4 z-50" 
        x-cloak x-show="viewGeneratedReport"
        @click.away="viewGeneratedReport = false">

        <div class="relative bg-white p-6 rounded-lg shadow-lg w-[90%] max-w-[1200px] h-[90%] flex flex-col overflow-hidden">
            <!-- Close Button -->
            <button 
                class="absolute top-2 right-2 bg-red-500 text-white px-3 py-1 rounded-full text-lg z-10"
                @click="viewGeneratedReport = false">
                ✕
            </button>

            <!-- Modal Title -->
            <p class="text-center text-xl font-semibold mb-4">GENERATED REPORT</p>

            <!-- PDF Display -->
            <template x-if="reportPath">
                <iframe 
                    :src="reportPath" 
                    class="flex-1 w-full rounded-lg border"
                    frameborder="0">
                </iframe>
            </template>
        </div>
    </div>

    @livewireScripts

</body>
</html>